version: '3.8'

services:
  # API Gateway
  api-gateway:
    image: shubham554/ayur-api-gateway:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - identity-service
      - catalog-service
      - order-service
      - ayurbot-service
      - notification-service
    networks:
      - ayur-network

  # Frontend (Next.js)
  frontend:
    image: shubham554/ayur-frontend:v4
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - ayur-network

  # Identity Service (Node.js)
  identity-service:
    image: shubham554/ayur-identity-service:v2
    environment:
      - PORT=3001
      - DB_HOST=postgres-db
      - DB_USER=user
      - DB_PASSWORD=password
      - JWT_SECRET=ayur_super_secret_key_2025
    depends_on:
      - postgres-db
    networks:
      - ayur-network

  # Catalog Service (Node.js)
  catalog-service:
    image: shubham554/ayur-catalog-service:latest
    environment:
      - PORT=3002
      - DB_HOST=postgres-db
      - DB_USER=user
      - DB_PASSWORD=password
      - JWT_SECRET=ayur_super_secret_key_2025
    depends_on:
      - postgres-db
    networks:
      - ayur-network

  # Order Service (Node.js)
  order-service:
    image: shubham554/ayur-order-service:v6
    build: ./order-service
    environment:
      - PORT=3003
      - DB_HOST=postgres-db
      - DB_USER=user
      - DB_PASSWORD=password
      - JWT_SECRET=ayur_super_secret_key_2025
    depends_on:
      - postgres-db
    networks:
      - ayur-network

  # Notification Service (Node.js)
  notification-service:
    image: shubham554/ayur-notification-service:v2
    container_name: microservices-notification-service-1
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_PORT=587
    ports:
      - "3004:3004"
    networks:
      - ayur-network

  # AyurBot Service (Python)
  ayurbot-service:
    image: shubham554/ayur-ayurbot-service:latest
    environment:
      - PORT=8000
      - GEMINI_API_KEY=AIzaSyDtKb4tUk131cnKEwfPr7caYqgsQSa0UyY
      - MONGO_URI=mongodb://mongo-db:27017
    ports:
      - "8000:8000"
    networks:
      - ayur-network

  # Databases
  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ayur_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./identity-service/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./catalog-service/migrations/init.sql:/docker-entrypoint-initdb.d/catalog_init.sql
      - ./order-service/migrations/init.sql:/docker-entrypoint-initdb.d/order_init.sql
      - ./backups/postgres_backup_20251130_233427_utf8.sql:/docker-entrypoint-initdb.d/99_restore.sql
      - ./backups:/backups
    networks:
      - ayur-network

  mongo-db:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
      - ./backups:/backups
    networks:
      - ayur-network

networks:
  ayur-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
